-- local colors = {
-- 	dark = "#000000",
-- 	red = "#9c333c",
-- 	grey = "#a0a1a7",
-- 	black = "#383a42",
-- 	white = "#f3f3f3",
-- 	blue = "#507791",
-- 	orange = "#8f7756",
-- 	green = "#339c70",
-- 	magent = "#b37944",
-- 	cyan = "#7e9c33",
-- 	insertcolor = "#578a3f",
-- 	visualcolor = "#754d5f",
-- 	replacecolor = "#9c67b5",
-- 	normalcolor = "#0f8a62",
-- 	color = "#1F5C50",
-- }
--
-- local theme = {
-- 	normal = {
-- 		a = { fg = colors.normalcolor, bg = colors.color },
-- 		b = { fg = colors.green, bg = colors.black },
-- 		c = { fg = colors.white, bg = colors.black },
-- 		z = { fg = colors.white, bg = colors.black },
-- 	},
-- 	insert = { a = { fg = colors.green, bg = colors.insertcolor } },
-- 	visual = { a = { fg = colors.green, bg = colors.visualcolor } },
-- 	replace = { a = { fg = colors.green, bg = colors.replacecolor } },
-- }
--
-- local space = {
-- 	function()
-- 		return ""
-- 	end,
-- 	color = { bg = colors.green, fg = colors.white },
-- }
--
-- local filename = {
-- 	"filename",
-- 	color = { bg = colors.green, fg = colors.dark, gui = "bold" },
-- 	separator = { right = "" },
-- }
--
-- local filetype = {
-- 	"filetype",
-- 	icons_enabled = false,
-- 	color = { bg = colors.blue, fg = colors.dark, gui = "italic,bold" },
-- 	separator = { right = "" },
-- }
--
-- local branch = {
-- 	"branch",
-- 	icon = "",
-- 	color = { bg = colors.cyan, fg = colors.dark, gui = "bold" },
-- 	separator = { right = "" },
-- }
--
-- local encoding = {
-- 	"encoding",
-- 	color = { bg = colors.red, fg = colors.dark, gui = "bold" },
-- 	separator = { right = "" },
-- }
--
-- local filesize = {
-- 	"filesize",
-- 	color = { bg = colors.orange, fg = colors.dark, gui = "bold" },
-- 	separator = { right = "" },
-- }
--
-- local location = {
-- 	"location",
-- 	color = { bg = colors.normalcolor, fg = colors.dark, gui = "bold" },
-- 	separator = { right = "" },
-- }
--
-- local diff = {
-- 	"diff",
-- 	color = { bg = colors.purple, fg = colors.blue, gui = "bold" },
-- 	separator = { left = "", right = "" },
-- 	symbols = { added = " ", modified = " ", removed = " " },
--
-- 	diff_color = {
-- 		added = { fg = colors.white },
-- 		modified = { fg = colors.white },
-- 		removed = { fg = colors.white },
-- 	},
-- }
--
-- local modes = {
-- 	"mode",
-- 	color = function()
-- 		local mode_color = colors
-- 		return { bg = mode_color[vim.fn.mode()], fg = colors.dark, gui = "bold" }
-- 	end,
-- 	separator = { right = "" },
-- }
--
-- local function getLspName()
-- 	local buf_clients = vim.lsp.buf_get_clients()
-- 	local buf_ft = vim.bo.filetype
-- 	if next(buf_clients) == nil then
-- 		return "  No servers"
-- 	end
-- 	local buf_client_names = {}
--
-- 	for _, client in pairs(buf_clients) do
-- 		if client.name ~= "null-ls" then
-- 			table.insert(buf_client_names, client.name)
-- 		end
-- 	end
--
-- 	local lint_s, lint = pcall(require, "lint")
-- 	if lint_s then
-- 		for ft_k, ft_v in pairs(lint.linters_by_ft) do
-- 			if type(ft_v) == "table" then
-- 				for _, linter in ipairs(ft_v) do
-- 					if buf_ft == ft_k then
-- 						table.insert(buf_client_names, linter)
-- 					end
-- 				end
-- 			elseif type(ft_v) == "string" then
-- 				if buf_ft == ft_k then
-- 					table.insert(buf_client_names, ft_v)
-- 				end
-- 			end
-- 		end
-- 	end
--
-- 	local ok, conform = pcall(require, "conform")
-- 	local formatters = table.concat(conform.list_formatters_for_buffer(), " ")
-- 	if ok then
-- 		for formatter in formatters:gmatch("%w+") do
-- 			if formatter then
-- 				table.insert(buf_client_names, formatter)
-- 			end
-- 		end
-- 	end
--
-- 	local hash = {}
-- 	local unique_client_names = {}
--
-- 	for _, v in ipairs(buf_client_names) do
-- 		if not hash[v] then
-- 			unique_client_names[#unique_client_names + 1] = v
-- 			hash[v] = true
-- 		end
-- 	end
-- 	local language_servers = table.concat(unique_client_names, ", ")
--
-- 	return "  " .. language_servers
-- end
--
-- local macro = {
-- 	require("noice").api.status.mode.get,
-- 	cond = require("noice").api.status.mode.has,
-- 	color = { fg = colors.red, bg = colors.blue, gui = "italic,bold" },
-- }
--
-- local dia = {
-- 	"diagnostics",
-- 	sources = { "nvim_diagnostic" },
-- 	symbols = { error = " ", warn = " ", info = " ", hint = " " },
-- 	diagnostics_color = {
-- 		error = { fg = colors.white },
-- 		warn = { fg = colors.white },
-- 		info = { fg = colors.white },
-- 		hint = { fg = colors.white },
-- 	},
-- 	color = { bg = colors.magent, fg = colors.black, gui = "bold" },
-- 	separator = { left = "" },
-- }
--
-- local lsp = {
-- 	function()
-- 		return getLspName()
-- 	end,
-- 	separator = { left = "" },
-- 	color = { bg = colors.red, fg = colors.dark, gui = "italic,bold" },
-- }
--
-- require("lualine").setup({
-- 	options = {
-- 		icons_enabled = true,
-- 		theme = theme,
-- 		component_separators = { left = "", right = "" },
-- 		section_separators = { left = "", right = "" },
-- 		disabled_filetypes = {
-- 			statusline = {},
-- 			winbar = {},
-- 		},
-- 		ignore_focus = {},
-- 		always_divide_middle = true,
-- 		globalstatus = true,
-- 	},
--
-- 	sections = {
-- 		lualine_a = {
-- 			modes,
-- 		},
-- 		lualine_b = {
-- 			space,
-- 		},
-- 		lualine_c = {
-- 			filename,
-- 			filetype,
-- 			space,
-- 			branch,
-- 			diff,
-- 			space,
-- 			location,
-- 			encoding,
-- 			filesize,
-- 		},
-- 		lualine_x = {
-- 			space,
-- 		},
-- 		lualine_y = { macro, space },
-- 		lualine_z = {
-- 			dia,
-- 			lsp,
-- 		},
-- 	},
-- 	inactive_sections = {
-- 		lualine_a = {},
-- 		lualine_b = {},
-- 		lualine_c = { "filename" },
-- 		lualine_x = { "location" },
-- 		lualine_y = {},
-- 		lualine_z = {},
-- 	},
-- })
